### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by biola1** [biola1/testingGit#1]
create a simple landing page on the index.html file

**Comment by modade23** [comment]
ok i will work on it right away.

**Comment by modade23** [comment]
@biola1

**Comment by sachinkumar2507** [comment]
hy i can help if you want

**Comment by biola1** [comment]
@sachinkumar2507 am new to devops....and am just learning.

**Comment by modade23** [comment]
@sachinkumar2507 you are welcome to help

**Comment by sachinkumar2507** [comment]
ok so can you tell me about the issue

**Comment by sachinkumar2507** [comment]
i have to create an landing page right

**Comment by sachinkumar2507** [comment]
assign me the issue
